# Generated by Django 3.0.7 on 2020-07-13 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(default='Uoen5N7dtJYpk5weWsUUcAHYH6gDecqDO6ZWTqJwuUkD1JkCp2mkHdn3bFN2UXSexkoV1v02nHS0EHi83h3EM92JYATaDZrgNuJU1KEIuMJbgmZk24kAOPbfogIfMaaz', max_length=128),
        ),
    ]
