# Generated by Django 3.0.7 on 2020-07-13 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0002_auto_20200713_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(default='2znU4mrrWMT1deVgAaVrtXwm212JGOpl92N2J323SSizb7AdTVFUErHAI37eM3z44IlpvMTBUJLFp04tyS4DMaMtQ7K6zBUb1sDHPEUKf8vWaa0hTyvSIQ1AcV0wEMMd', max_length=128),
        ),
    ]
